// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGZ8tI_qj2rZnZrTPVROD5L1CF3M1PkH8',
    appId: '1:859830987876:web:44de6723dfade36163c371',
    messagingSenderId: '859830987876',
    projectId: 'kapit-bahay',
    authDomain: 'kapit-bahay.firebaseapp.com',
    storageBucket: 'kapit-bahay.firebasestorage.app',
    measurementId: 'G-2ZNQYFQPGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsmOG3Z1oSBD-sKNUDILs-xiKiTAhEvQE',
    appId: '1:859830987876:android:82205300424b1ee663c371',
    messagingSenderId: '859830987876',
    projectId: 'kapit-bahay',
    storageBucket: 'kapit-bahay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwVgI5FVo3-b9AlV8h3XJZk6ruU7ENUwc',
    appId: '1:859830987876:ios:dfbec3b2daa5165a63c371',
    messagingSenderId: '859830987876',
    projectId: 'kapit-bahay',
    storageBucket: 'kapit-bahay.firebasestorage.app',
    iosBundleId: 'com.example.kapitbahayapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwVgI5FVo3-b9AlV8h3XJZk6ruU7ENUwc',
    appId: '1:859830987876:ios:dfbec3b2daa5165a63c371',
    messagingSenderId: '859830987876',
    projectId: 'kapit-bahay',
    storageBucket: 'kapit-bahay.firebasestorage.app',
    iosBundleId: 'com.example.kapitbahayapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGZ8tI_qj2rZnZrTPVROD5L1CF3M1PkH8',
    appId: '1:859830987876:web:be9a3d8719ca282d63c371',
    messagingSenderId: '859830987876',
    projectId: 'kapit-bahay',
    authDomain: 'kapit-bahay.firebaseapp.com',
    storageBucket: 'kapit-bahay.firebasestorage.app',
    measurementId: 'G-PVRW0LQNXR',
  );
}
